KTCL13/Quejas-Entidades-BOY

README.md
middleware/recaptcha.js
migrations/20250908161928-create-quejas.js
models/Queja.js

Se añade el campo isDeleted_queja en modelo para agregarlo en la base de datos
- Cierra #46 
2. Se probó que el nuevo campo es añadido exitosamente

add: añadir campo isDeleted_queja en modelo y migración

---

migrations/20250908161921-create-entities.js
migrations/20250908161928-create-quejas.js
models/Entity.js
models/index.js
routes/listaQuejas.js
routes/quejas.js
seeders/20250908160117-demo-entidades.js
services/quejas.service.js
views/lista-quejas.pug
views/registrar.pug
views/reportes.pug

Se traduce "Entidades" por "Entities" en el modelo y en las migraciones sequalize

Se traduce "Entidades" por "Entities" en el modelo y en las migraciones sequalize

---

middleware/recaptcha.js

Se cambia un espacio que impedía leer correctamente la variable de entorno NOVE_ENV en la verificación del recaptcha

Se corrige error al verificar recapcha en entorno de desarrollo

---

models/Complaint.js
models/index.js
services/quejas.service.js

Se cambia el nombre del archivo models/Quejas por Complaints

Se cambia el nombre del archivo models/Quejas por Complaints

---

migrations/20250908161928-create-complaints.js
models/Complaint.js
models/index.js
routes/quejas.js
services/quejas.service.js
test-jest/quejas.test.js
views/lista-quejas.pug
views/registrar.pug

Se cambia el nombre "quejas" en el modelo de la base de datos por Complaits" se actualiza el nombre de las columnas y las migraciones

Se cambia el nombre "quejas" en el modelo de la base de datos por Complaits"

---

docker-compose.yml
views/layout.pug
views/lista-quejas.pug

...
- Cierra # (57)
2. Navegué a la ruta `/ejemplo`.
3. Verifiqué que el nuevo componente se renderiza correctamente.
...

Se agrega botón para eliminar queja en lista-quejas

---

routes/quejas.js
services/quejas.service.js

Se agrega el servicio para borrado lógico de quejas y se implementa en en routes/quejas según el requisito
- Cierra #50 

Se agrega el servicio para borrado lógico de quejas

---

config/cache.js
routes/listaQuejas.js
routes/quejas.js
services/quejas.service.js
test-jest/quejas.test.js

se cambian el nombre de las funciones set y get de la clase asi como la listas para guardar.
- Cierra # (número del issue)
3. Verifiqué que el  componente se renderiza correctamente.

Se traduce el archivo config/cache.js al ingles

---

routes/quejas.js
services/quejas.service.js

Se crea un endpoint para obtener una queja por su ID (GET) api/quejas/:id
- Cierra #101 
2. Navegué a la ruta `api/quejas/2`.
3. Verifiqué que la queja es traida correctamente.}
**Pruebas automáticas: **

Se crea un endpoint para obtener una queja por su ID

---

public/js/mainComment.js

se modifica la ruta del fetch y el nombre del campo en el body e mainComment.js
- Cierra # (número del issue)

se arregla el fetch de los comentarios desde una queja

---

migrations/20250922021903-create-comments.js
models/Comment.js
models/index.js

Se crea la tabla Comments y se establece la relación con Complaints. Se actualizan las migraciones
- Cierra #102
1. reinicie la base de datos con `npm run db:restet`.
2. Comprobé que la tabla estaba creada y tenía las relaciones correctas.

Se crea la tabla Comments y se establece la relación con Complaints.

---

migrations/20250922021903-create-comments.js

Se corrigen las migraciones de Comments para incluir los campos faltantes de createdAt y updatedAt.
1. Se comprobaron los nuevos campos en la base de datos.

Se corrigen las migraciones de Comments

---

migrations/20250922021903-create-comments.js
models/Comment.js

Se corrige disparidad en nombres de modelos y tablas por creacion automatica de Sequelize con timestamps=true

Se corrige disparidad en nombres de modelos y tablas

---

views/comment.pug

Se agregó la interfaz de modal para cambiar el estado de una queja
- Cierra # (95)
- [X ] ✨ Nueva funcionalidad (Nueva característica)
...

agregar modal para cambio de estado

---

interfaces/IMailService.js

se crea un interfaz para el servicio de correo que define el contrato que deben seguir las implementaciones concretas.
- Cierra #23

se crea un interfaz para el servicio de correo

---

services/nodemailer.service.js

Se crea el servicio de nodemailer que implementa la interfaz IMailService. 
- Cierra #24

Se crea el servicio de nodemailer 

---

public/js/main.js
views/lista-quejas.pug

Se cambia compliantList para agregar una columna que muestra el estado actual de la queja.
- Cierra #98 
2. Navegué a la ruta `/`.
3. Verifiqué que el nuevo componente se renderiza correctamente.

Se añade el estado de la queja en la lista de quejas

---

public/js/main.js
services/quejas.service.js

Se implementa la interfaz de paginación en la lista de quejas por entidad
- Cierra #137 
2. Navegué a la ruta `/`.
3. Verifiqué que el nuevo componente se renderiza correctamente.

Se implementa la interfaz de paginación en la lista de quejas

---

test-jest/reportes.test.js

pruebas unitarias
- Cierra # (146)
- [ X] ✅ Pruebas (Pruebas)

Pruebas unitarias para reportes.js

---

README.md
services/nodemailer.service.js

Se actualiza el servicio de Nodemailer para que sea dinamica la seleccion del provedor de correos.

Refactor nodemailer service

---

docker-compose.yml
public/js/main.js
views/lista-quejas.pug

Se crea la lista desplegable para ver comentario y elimnar queja con js, modificando main.js 
...
- Cierra #152 
2. Navegué a la ruta `/ejemplo`.
3. Verifiqué que el nuevo componente se renderiza correctamente.
...

se crea la lista desplegable

---

routes/comments.js
test-jest/comments.test.js

Se cambia la respuesta de POST api/comments/complaints/:id para que devuelva el comentario creado en formato JSON.
- Cierra # (número del issue)

Se cambia la respuesta de POST api/comments/complaints/:id
